- id: "restostaff"
  title: "Heilungsstab von Thurwe"
  description: "Ein Stab im Stil der Nord."
  image: "/assets/25_01_reward.png"
  rarity: "common"
- id: "craftingtable"
  title: "Alchemietisch von Ursalette"
  description: "Ein robuster Tisch, gezeichnet von Jahren voller Tinkturen und Experimente."
  image: "/assets/25_02_reward.png"
  rarity: "epic"
- id: "stardew"
  title: "Sternentau von K'ren-Dar"
  description: "Eine Flasche Wasser, die leicht schimmert."
  image: "/assets/25_03_reward.png"
  rarity: "common"
- id: "shields"
  title: "Schilde von Malerics Gefährten"
  description: "Schilde von Pakt, Bündnis und Dominion."
  image: "/assets/25_04_reward.png"
  rarity: "uncommon"
- id: "nickel"
  title: "Nickel von Ciira"
  description: "Material, das die Essenz der Kaiserlichen verkörpert."
  image: "/assets/25_05_reward.png"
  rarity: "common"
