- id: "restostaff"
  title: "Thurwe's Restoration Staff"
  description: "A staff in the nordic style."
  image: "/assets/25_01_reward.png"
  rarity: "common"
- id: "craftingtable"
  title: "Ursalette's Alchemy Workbench"
  description: "A sturdy table stained with years of tinctures and experiments."
  image: "/assets/25_02_reward.png"
  rarity: "epic"
- id: "stardew"
  title: "K'ren-Dar's Stardew"
  description: "A bottle of water that shimmers slightly."
  image: "/assets/25_03_reward.png"
  rarity: "common"
- id: "shields"
  title: "Shields of Maleric's companions"
  description: "Shields of Pact, Covenant and Dominion."
  image: "/assets/25_04_reward.png"
  rarity: "uncommon"
- id: "nickel"
  title: "Ciira's nickel"
  description: "Material that embodies the essence of the Imperials."
  image: "/assets/25_05_reward.png"
  rarity: "common"
- id: "starmetal"
  title: "Enniz's starmetal"
  description: "Material that embodies the essence of the Redguards."
  image: "/assets/25_06_reward.png"
  rarity: "common"
- id: "weaponskills"
  title: "Magrub's skills"
  description: "Some useful skills."
  image: "/assets/25_07_reward.png"
  rarity: "common"
- id: "glyph"
  title: "Lytril's glyph"
  description: "A powerful enchantment."
  image: "/assets/25_08_reward.png"
  rarity: "common"
- id: "plants"
  title: "Estile's alchemical plants"
  description: "A few rare plants."
  image: "/assets/25_09_reward.png"
  rarity: "rare"
- id: "ingredients"
  title: "Falemon's alchemical ingredients"
  description: "A few rare ingredients."
  image: "/assets/25_10_reward.png"
  rarity: "rare"
- id: "moonstone"
  title: "N'aabi's Moonstone"
  description: "Material that embodies the essence of the Khajiit."
  image: "/assets/25_11_reward.png"
  rarity: "common"
- id: "obsidian"
  title: "Erendas' Obsidian"
  description: "Material that embodies the essence of the Dark Elves."
  image: "/assets/25_12_reward.png"
  rarity: "common"
- id: "wardenskills"
  title: "Logorok's skills"
  description: "Some warden skills."
  image: "/assets/25_13_reward.png"
  rarity: "common"
- id: "soultrap"
  title: "Hilthe's Soul Trap"
  description: "A skill that allows you to trap the soul of a slain enemy."
  image: "/assets/25_14_reward.png"
  rarity: "common"
- id: "key"
  title: "Oraar's key"
  description: "A key made by the Undaunted."
  image: "/assets/25_15_reward.png"
  rarity: "uncommon"
- id: "nirncrux"
  title: "Razaami's nirncrux"
  description: "A chunk of raw nirncrux."
  image: "/assets/25_16_reward.png"
  rarity: "epic"
- id: "runes"
  title: "Itium's"
  description: "Some runestones."
  image: "/assets/25_17_reward.png"
  rarity: "epic"
- id: "voucher"
  title: "Uralest's voucher"
  description: "A writ voucher."
  image: "/assets/25_18_reward.png"
  rarity: "uncommon"
- id: "armorskill"
  title: "Latharek's skill"
  description: "A skill that allows one to protect oneself."
  image: "/assets/25_19_reward.png"
  rarity: "common"
- id: "weapons"
  title: "Gin-Ei's weapons"
  description: "A daggar and an axe in the celestial style."
  image: "/assets/25_20_reward.png"
  rarity: "uncommon"
- id: "alliance-points"
  title: "Vilonia's alliance points"
  description: "A hand full of alliance points."
  image: "/assets/25_21_reward.png"
  rarity: "common"
- id: "taunt"
  title: "Telnidra's skill"
  description: "A skill that can be used to taunt an enemy."
  image: "/assets/25_22_reward.png"
  rarity: "common"
- id: "potion"
  title: "A potion"
  description: "A potion you have crafted yourself."
  image: "/assets/25_23_reward.png"
  rarity: "uncommon"
